    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    joint1_effort_controller:
        type: effort_controllers/JointPositionController
        joint: jaco_joint_1
        pid: {p: 2400.0, i: 0.0, d: 18.0}

    joint2_effort_controller:
        type: effort_controllers/JointEffortController
        joint: jaco_joint_2
        pid: {p: 1000.0, i: 0.0, d: 6.0}

    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: jaco_joint_3
        pid: {p: 1000.0, i: 0.0, d: 6.0}

    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: jaco_joint_4
        pid: {p: 700.0, i: 0.0, d: 4.0}

    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: jaco_joint_5
        pid: {p: 300.0, i: 0.0, d: 6.0}

    joint6_position_controller:
        type: effort_controllers/JointPositionController
        joint: jaco_joint_6
        pid: {p: 300.0, i: 0.0, d: 4.0}

 
